Add GigabiteLabs support to README
cloudant/swift-cloudant pull request #195
Opened 2022-01-25 12:55 UTC by vmatyusGitHub

## Checklist

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [ ] Added tests for code changes _or_ test/build only changes
- [ ] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [x] Completed the PR template below:

## Description
Fixes #194 

README change that mentions library support is continued by GigabiteLabs.

2022-01-25 13:52 UTC, ricellis requested changes

2022-01-25 13:52 UTC, ricellis commented on README.md
> +**This library is now deprecated and not supported by IBM.**
I don't think we need to say IBM, it isn't supported by anyone in this repo.
```suggestion
**This library is end-of-life and no longer supported.**
```

2022-01-25 13:52 UTC, ricellis commented on README.md
> +Please visit their forked version with your concern: https://github.com/GigabiteLabs/swift-cloudant-lts
I think we should be more vague here, the `README` in the archived repo might long outlast any given fork and new forks may emerge.
```suggestion
Please see the list of [forks](https://github.com/cloudant/swift-cloudant/network/members) for continuing development efforts (e.g. #194).
```

2022-01-25 16:27 UTC, vmatyusGitHub commented on README.md
> +Please visit their forked version with your concern: https://github.com/GigabiteLabs/swift-cloudant-lts
Changed in 5e0f275

2022-01-26 07:51 UTC, vmatyusGitHub commented on README.md
> +Please visit their forked version with your concern: https://github.com/GigabiteLabs/swift-cloudant-lts
Also removed the first sentence: 698734b

2022-01-26 08:04 UTC, mojito317 approved these changes

2022-01-26 10:01 UTC, ricellis approved these changes
Thanks @vmatyusGitHub , please squash the commits and then I'll merge it.

2022-01-26 10:13 UTC, vmatyusGitHub commented
Finished with the squashing.

2022-01-26 14:11 UTC, merged